### ISSUE TITLE
Evolution Workshop Planning

### ISSUE THREAD

**Issue by tjv** [phenoscape/cate#6]

**Comment by tjv** [comment]
Goal: a pre-conference workshop to train target audience in ontologies and their use for evobio.
Structure: half day before/during 2019 meeting (Providence RI, June 21-25), full day in future yrs.
Steps: 
* draft abstract
* share w/ organizers, inquire about coordinating w/ space/registration of main meeting. 
* come up with budget for participants, on-site costs, figure out registration costs if any
* schedule presenters

**Comment by tjv** [comment]
**To Dos** from [course planning doc](https://docs.google.com/document/d/1Lbn59al2gAB33Wm2yLMIvqGGoNdTaqrGnt6jbPoS6aY/edit#)
- Hilmar to set up Jeckyll site
- Todd to modify agenda, outline - populate before May 1st
- Wasila to identify test dataset
- Wasila catering and AV
- Send out additional rounds of announcement May 1 and May 7

**Comment by hlapp** [comment]
The workshop was held at the 2019 Evolution Meetings.
